#!/usr/bin/env python3
import sys
from os import walk
from os import path
from os import chdir
from os import rename
from shutil import chown
from fnmatch import fnmatch
from functools import reduce
from time import time
from os import environ

# produces an index. Format:
# <total count> <total size> <timestamp>
# <size> <path>
# <size> <path>
# ...

root = environ["ASTRALBROWSER_ROOT"]
user = environ["ASTRALBROWSER_USER"]
indexfile = path.join(root, ".index.txt")
indextmp = path.join(root, ".index-tmp.txt")

# adapted from my git ignores
ignores = [
    ".envrc",
    ".fseventsd",
    "*-r",
    "*.__i",
    "*.acn",
    "*.acr",
    "*.alg",
    "*.autosave",
    "*.aux",
    "*.axf",
    "*.bak",
    "*.bbl",
    "*.bin",
    "*.blg",
    "*.build/",
    "*.class",
    "*.crf",
    "*.d",
    "*.dep",
    "*.dist/",
    "*.dll",
    "*.dmg",
    "*.dvi",
    "*.egg-info",
    "*.glg",
    "*.glo",
    "*.gls",
    "*.gz",
    "*.hex",
    "*.idx",
    "*.ilg",
    "*.ind",
    "*.iso",
    "*.ist",
    "*.jar",
    "*.lnp",
    "*.lof",
    "*.lot",
    "*.lst",
    "*.luac",
    "*.maf",
    "*.map",
    "*.mtc",
    "*.mtc1",
    "*.o",
    "*.onefile-build/",
    "*.out",
    "*.plg",
    "*.pyc",
    "*.pyg",
    "*.rar",
    "*.retry",
    "*.so",
    "*.synctex.gz",
    "*.tar",
    "*.toc",
    "*.tra",
    "*.uvopt",
    "*.uvproj",
    "*.zip",
    "*~",
    ".*.swp",
    ".AppleDouble",
    ".Parent",
    ".DS_Store",
    ".DS_Store?",
    ".Python",
    ".Spotlight-V100",
    ".Trashes",
    "._*",
    ".build/",
    ".coverage*",
    ".direnv/",
    ".hugo_build.lock",
    ".tox",
    ".venv",
    ".~lock.*",
    "Icon?",
    "Thumbs.db",
    "__pycache__",
    "_build",
    "coverage.txt",
    "coverage.xml",
    "coverage_html",
    "dist",
    "dump.rdb",
    "ehthumbs.db",
    "env",
    "node_modules/",
    "pip-selfcheck.json",
    "result",
    "venv",
    "xcuserdata",
    "~$*",
    ".git",
]

MIN_SIZE = 1024 # 1KB

chdir(root)

# list of tuples: (size, path)
#file_list: list[tuple[int, str]] = []
file_list = []  # older python!

for dirpath, dirnames, filenames in walk(".", followlinks=True):
    for filename in filenames:
        if any(fnmatch(filename, ignore) for ignore in ignores):
            continue

        if any(fnmatch(path.basename(dirpath), ignore) for ignore in ignores):
            continue

        filepath = path.join(dirpath, filename)

        try:
            size = path.getsize(filepath)
        except FileNotFoundError:
            continue

        # no possible use for these files
        if size < MIN_SIZE:
            continue

        file_list.append((size, filepath))

# biggest first (user probably wants media, not .c files from some random repository)
file_list.sort(key=lambda x: x[0], reverse=True)

total_size = reduce(lambda acc, item: acc + item[0], file_list, 0)

with open(indextmp, "w") as f:
    f.write("%d %d %d\n" % (len(file_list), total_size, int(time())))

    for size, filepath in file_list:
        f.write("%d %s\n" % (size, filepath))

# atomic update
rename(indextmp, indexfile)
chown(indexfile, user, user)
