#!/usr/bin/env python3
import sys
from os import walk
from os import path
from os import chdir
from os import rename
from shutil import chown
from fnmatch import fnmatch
from functools import reduce
from time import time
from os import environ

# produces an index. Format:
# <total count> <total size> <timestamp>
# <size> <path>
# <size> <path>
# ...

root = environ["ASTRALBROWSER_ROOT"]
user = environ["ASTRALBROWSER_USER"]
indexfile = path.join(root, ".index.txt")
indextmp = path.join(root, ".index-tmp.txt")

# 24h matches the systemd timer interval -- if the sub-index is older than one
# cycle, it's overdue for a refresh and we should crawl instead
MAX_INDEX_AGE_S = 24 * 3600

# adapted from my git ignores
ignores = [
    ".envrc",
    ".fseventsd",
    "*-r",
    "*.__i",
    "*.acn",
    "*.acr",
    "*.alg",
    "*.autosave",
    "*.aux",
    "*.axf",
    "*.bak",
    "*.bbl",
    "*.bin",
    "*.blg",
    "*.build/",
    "*.class",
    "*.crf",
    "*.d",
    "*.dep",
    "*.dist/",
    "*.dll",
    "*.dmg",
    "*.dvi",
    "*.egg-info",
    "*.glg",
    "*.glo",
    "*.gls",
    "*.gz",
    "*.hex",
    "*.idx",
    "*.ilg",
    "*.ind",
    "*.iso",
    "*.ist",
    "*.jar",
    "*.lnp",
    "*.lof",
    "*.lot",
    "*.lst",
    "*.luac",
    "*.maf",
    "*.map",
    "*.mtc",
    "*.mtc1",
    "*.o",
    "*.onefile-build/",
    "*.out",
    "*.plg",
    "*.pyc",
    "*.pyg",
    "*.rar",
    "*.retry",
    "*.so",
    "*.synctex.gz",
    "*.tar",
    "*.toc",
    "*.tra",
    "*.uvopt",
    "*.uvproj",
    "*.zip",
    "*~",
    ".*.swp",
    ".AppleDouble",
    ".Parent",
    ".DS_Store",
    ".DS_Store?",
    ".Python",
    ".Spotlight-V100",
    ".Trashes",
    "._*",
    ".build/",
    ".coverage*",
    ".direnv/",
    ".hugo_build.lock",
    ".tox",
    ".venv",
    ".~lock.*",
    "Icon?",
    "Thumbs.db",
    "__pycache__",
    "_build",
    "coverage.txt",
    "coverage.xml",
    "coverage_html",
    "dist",
    "dump.rdb",
    "ehthumbs.db",
    "env",
    "node_modules/",
    "pip-selfcheck.json",
    "result",
    "venv",
    "xcuserdata",
    "~$*",
    ".git",
]


def try_read_sub_index(index_path, dirpath):
    """If index_path is a valid, recent .index.txt, return its entries with
    paths rewritten to be relative to the root. Returns None on any failure."""
    try:
        with open(index_path, "r") as f:
            header = f.readline()
            fields = header.strip().split(" ")
            if len(fields) != 3:
                return None

            timestamp = int(fields[2])
            age = time() - timestamp
            if age > MAX_INDEX_AGE_S or age < 0:
                return None

            entries = []
            for line in f:
                line = line.strip()
                if not line:
                    continue
                # format: "<size> <relpath>"
                space = line.index(" ")
                size = int(line[:space])
                entry_path = line[space + 1:]
                # entry_path is relative to the sub-index dir (e.g. ./foo/bar),
                # rewrite to be relative to root
                if entry_path.startswith("./"):
                    entry_path = entry_path[2:]
                entries.append((size, path.join(dirpath, entry_path)))

            print("using sub-index: %s (%s entries)" % (index_path, len(entries)), file=sys.stderr)
            return entries
    except (OSError, ValueError, IndexError):
        return None


chdir(root)

# list of tuples: (size, path)
#file_list: list[tuple[int, str]] = []
file_list = []  # older python!

for dirpath, dirnames, filenames in walk(".", followlinks=True):
    # Skip the root's own .index.txt -- that's the file we're writing
    if dirpath != ".":
        sub_index = path.join(dirpath, ".index.txt")
        if path.isfile(sub_index):
            entries = try_read_sub_index(sub_index, dirpath)
            if entries is not None:
                file_list.extend(entries)
                # don't descend into this subtree, the sub-index covers it
                dirnames.clear()
                continue

    for filename in filenames:
        if any(fnmatch(filename, ignore) for ignore in ignores):
            continue

        if any(fnmatch(path.basename(dirpath), ignore) for ignore in ignores):
            continue

        filepath = path.join(dirpath, filename)

        try:
            size = path.getsize(filepath)
        except FileNotFoundError:
            continue

        file_list.append((size, filepath))

# biggest first (user probably wants media, not .c files from some random repository)
file_list.sort(key=lambda x: x[0], reverse=True)

total_size = reduce(lambda acc, item: acc + item[0], file_list, 0)

with open(indextmp, "w") as f:
    # header
    f.write("%d %d %d\n" % (len(file_list), total_size, int(time())))

    for size, filepath in file_list:
        f.write("%d %s\n" % (size, filepath))

# atomic update
rename(indextmp, indexfile)
chown(indexfile, user, user)
