#!/usr/bin/env python3
import sys
from subprocess import run, PIPE
from os.path import join

if len(sys.argv) != 3:
    print("Usage: %s <what> <where>" % sys.argv[0])
    print("\nMount an nfs share with systemd, reliably")
    sys.exit(1)


def escape(path):
    return (
        run(["systemd-escape", "--path", path], check=True, stdout=PIPE)
        .stdout.decode()
        .strip()
    )


def run_cmd(cmd):
    print(run(cmd, check=True, stdout=PIPE).stdout.decode().strip())


what = sys.argv[1]
where = sys.argv[2]

systemd_unit_dir = "/etc/systemd/system"


mount_template = """[Unit]
Description={description}
After=nss-lookup.target

[Mount]
What={what}
Where={where}
Options=ro,soft,bg,vers=4
Type=nfs
TimeoutSec=10

[Install]
WantedBy=multi-user.target
"""

automount_template = """[Unit]
Description={description}

[Automount]
Where={where}
TimeoutIdleSec=600

[Install]
WantedBy=multi-user.target
"""

with open(join(systemd_unit_dir, escape(where) + ".mount"), "w") as f:
    f.write(mount_template.format(description=where, what=what, where=where))

with open(join(systemd_unit_dir, escape(where) + ".automount"), "w") as f:
    f.write(automount_template.format(description=where, where=where))

run_cmd(["systemctl", "daemon-reload"])
run_cmd(["systemctl", "start", escape(where) + ".automount"])
run_cmd(["systemctl", "enable", escape(where) + ".automount"])
