#!/usr/bin/env python3
import sys
from subprocess import check_output

# TODO implement

if len(sys.argv) != 2:
    print("Usage: %s <file>" % sys.argv[0])
    sys.exit(1)

# todo see naggie-hugo-theme for pope through command implementation
def escape_string(string):
    out = check_output(["systemd-escape"])

template = """
[Unit]
Description=user share
# as we're using DNS hostnames....
After=nss-lookup.target
# Could put dsnet service here as an After= dependency, but this machine does
# not use dsnet for the VPN as it has a direct connection.

[Mount]
What=grendelkeep.***REMOVED***.io:/srv/software
# must match file name (escaped with systemd-escape!)
Where=/mnt/shares/naggie
Options=ro,soft,bg,vers=4
Type=nfs
TimeoutSec=10

[Install]
WantedBy=multi-user.target
"""
