#!/usr/bin/env python3
import sys
from subprocess import run, PIPE
from os import makedirs, path

if len(sys.argv) != 3:
    print("Usage: %s <what> <where>" % sys.argv[0])
    print("\nMount an nfs share with systemd, reliably")
    sys.exit(1)


def escape(path):
    return (
        run(["systemd-escape", "--path", path], check=True, stdout=PIPE)
        .stdout.decode()
        .strip()
    )


what = sys.argv[1]
where = sys.argv[2]

systemd_unit_dir = "/etc/systemd/system"


mount_template = """[Unit]
Description={description}
After=nss-lookup.target

[Mount]
What={what}
Where={where}
Options=ro,soft,bg,vers=4
Type=nfs
TimeoutSec=10

[Install]
WantedBy=multi-user.target
"""

automount_template = """[Unit]
Description={description}

[Automount]
Where={where}

[Install]
WantedBy=multi-user.target
"""

makedirs(where, exist_ok=True)

with open(path(systemd_unit_dir, escape(path) + ".mount")) as f:
    f.write(mount_template.format(description=where, what=what, where=where))

with open(path(systemd_unit_dir, escape(path) + ".automount")) as f:
    f.write(mount_template.format(description=where, where=where))

run(["systemctl", "daemon-reload"])
run(["systemctl", "start", escape(path) + ".automount")
run(["systemctl", "enable", escape(path) + ".automount")
