#!/usr/bin/env bash
set -e

BASE=/mnt/user-shares
INDEX=${BASE}/.index
INDEXTMP=${BASE}/.index.tmp

# NOTE when serving with nginx, ensure the location has gzip enabled

cd $BASE
find . -type f -not -path '*/.*' > ${INDEXTMP}
mv ${INDEXTMP} ${INDEX}
chown www-data:www-data ${INDEX}
